"""empty message

Revision ID: bb3bf3a62ffc
Revises: cc56d2161cee
Create Date: 2018-03-14 16:58:34.944226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3bf3a62ffc'
down_revision = 'cc56d2161cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_email', table_name='member')
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=False)
    op.drop_index('ix_member_link_vcf', table_name='member')
    op.create_index(op.f('ix_member_link_vcf'), 'member', ['link_vcf'], unique=False)
    op.drop_index('ix_member_phone_number', table_name='member')
    op.create_index(op.f('ix_member_phone_number'), 'member', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_phone_number'), table_name='member')
    op.create_index('ix_member_phone_number', 'member', ['phone_number'], unique=1)
    op.drop_index(op.f('ix_member_link_vcf'), table_name='member')
    op.create_index('ix_member_link_vcf', 'member', ['link_vcf'], unique=1)
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.create_index('ix_member_email', 'member', ['email'], unique=1)
    # ### end Alembic commands ###
