"""users table

Revision ID: cc56d2161cee
Revises: 
Create Date: 2018-03-14 16:16:04.985660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc56d2161cee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('division', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('link_vcf', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_company'), 'member', ['company'], unique=False)
    op.create_index(op.f('ix_member_division'), 'member', ['division'], unique=False)
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=True)
    op.create_index(op.f('ix_member_full_name'), 'member', ['full_name'], unique=True)
    op.create_index(op.f('ix_member_link_vcf'), 'member', ['link_vcf'], unique=True)
    op.create_index(op.f('ix_member_location'), 'member', ['location'], unique=False)
    op.create_index(op.f('ix_member_phone_number'), 'member', ['phone_number'], unique=True)
    op.create_index(op.f('ix_member_role'), 'member', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_role'), table_name='member')
    op.drop_index(op.f('ix_member_phone_number'), table_name='member')
    op.drop_index(op.f('ix_member_location'), table_name='member')
    op.drop_index(op.f('ix_member_link_vcf'), table_name='member')
    op.drop_index(op.f('ix_member_full_name'), table_name='member')
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.drop_index(op.f('ix_member_division'), table_name='member')
    op.drop_index(op.f('ix_member_company'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
